name: containerimage

on:
  push:
    branches: main

jobs:
  app:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.CR_USERNAME }}
          password: ${{ secrets.CR_PAT }}

      - name: fetch repository
        uses: actions/checkout@master
      - name: Set GITHUB_SHA_SHORT
        run: echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV
      
      - name: test app
        uses: cedrickring/golang-action@1.6.0
        env:
          PROJECT_PATH: "app/"
        with:
          args: go test -race -timeout 5s .

      - name: build app
        uses: cedrickring/golang-action@1.6.0
        env:
          PROJECT_PATH: "app/"
          CGO_ENABLED: "0" 
        with:
          args: go build -ldflags \"-X main.Version=${{ env.GITHUB_SHA_SHORT }}\" .

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: ./app
          file: ./app/Dockerfile
          push: true
          tags: |
            ghcr.io/aau-claaudia/dirtyci:${{ env.GITHUB_SHA_SHORT }}

  deploy:
    runs-on: ubuntu-latest
    needs: app
    environment:
      name: Production
      url: http://130.226.98.55
    steps:
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: all.yml
          directory: ${GITHUB_WORKSPACE}/ansible
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          inventory: |
            [all]
            webserver ansible_port=443 ansible_host=130.226.98.55 ansible_user=ubuntu ansible_become=yes
          options: |
            --verbose