name: containerimage

on:
  push:
    branches: master

jobs:
  app:
    runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@master
      
      - name: run
        uses: cedrickring/golang-action@1.6.0
        env:
          PROJECT_PATH: "app/"
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./app
          file: ./app/Dockerfile
          push: true
          tags: |
            ghcr.io/aau-claaudia/DirtyCI:latest