name: containerimage

on:
  push:
    branches: main

jobs:
  app:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.CR_USERNAME }}
          password: ${{ secrets.CR_PAT }}

      - name: fetch repository
        uses: actions/checkout@master
      - name: Set GITHUB_SHA_SHORT
        run: echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV
      
      - name: test app
        uses: cedrickring/golang-action@1.6.0
        env:
          PROJECT_PATH: "app/"
        with:
          args: go test -race -timeout 5s .

      - name: build app
        uses: cedrickring/golang-action@1.6.0
        env:
          PROJECT_PATH: "app/"
          CGO_ENABLED: "0" 
        with:
          args: go build -ldflags \"-X main.Version=${{ env.GITHUB_SHA_SHORT }}\" .

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: ./app
          file: ./app/Dockerfile
          push: true
          tags: |
            ghcr.io/aau-claaudia/dirtyci:${{ env.GITHUB_SHA_SHORT }}

  deploy:
    runs-on: ubuntu-latest
    needs: app
    environment:
      name: Production
      url: http://130.226.98.55
    env: 
      SSH_AUTH_SOCK: /tmp/ssh_agent.sock
    steps:
      - name: fetch repository
        uses: actions/checkout@master
      - name: Play Ansible Playbook
        uses: arillso/action.playbook@master
        with:
          playbook: ansible/playbook.yml
          inventory: ansible/inventory
          private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_common_args: "\"-oUserKnownHostsFile=known_hosts\""
      # quick and dirty image update, we should manage a complete service spec and deploy it
      - name: update service spec
        run: | 
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
          ssh 130.226.98.55 \
            -o UserKnownHostsFile=known_hosts \
            -p443 -lubuntu \
            docker service update dirtyci --image ghcr.io/aau-claaudia/dirtyci:${{ env.GITHUB_SHA_SHORT }}
        